// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef camera_menu_hpp
#define camera_menu_hpp
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input_Choice.H>
#include <FL/Fl_Button.H>

class CameraMenu {
public:
  CameraMenu();
};
#endif
