// generated by Fast Light User Interface Designer (fluid) version 1.0400

#include "camera_menu.hpp"

CameraMenu::CameraMenu() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(630, 125, "Camera Menu");
    w = o; if (w) {/* empty */}
    o->user_data((void*)(this));
    { Fl_Input_Choice* o = new Fl_Input_Choice(5, 25, 210, 25, "Display");
      o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
    } // Fl_Input_Choice* o
    { new Fl_Button(5, 65, 120, 30, "Show");
    } // Fl_Button* o
    o->end();
  } // Fl_Double_Window* o
}
