// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef camera_menu_h
#define camera_menu_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>

class CameraWindow {
public:
  Fl_Double_Window* make_window();
  Fl_Input *m_camera1_script;
  Fl_Input *m_camera2_script;
  Fl_Input *m_camera3_script;
  Fl_Button *m_run1;
private:
  inline void cb_m_run1_i(Fl_Button*, void*);
  static void cb_m_run1(Fl_Button*, void*);
public:
  Fl_Button *m_run2;
private:
  inline void cb_m_run2_i(Fl_Button*, void*);
  static void cb_m_run2(Fl_Button*, void*);
public:
  Fl_Button *m_run3;
private:
  inline void cb_m_run3_i(Fl_Button*, void*);
  static void cb_m_run3(Fl_Button*, void*);
public:
  Fl_Button *m_Browse1;
private:
  inline void cb_m_Browse1_i(Fl_Button*, void*);
  static void cb_m_Browse1(Fl_Button*, void*);
public:
  Fl_Button *m_Browse2;
private:
  inline void cb_m_Browse2_i(Fl_Button*, void*);
  static void cb_m_Browse2(Fl_Button*, void*);
public:
  Fl_Button *m_Browse3;
private:
  inline void cb_m_Browse3_i(Fl_Button*, void*);
  static void cb_m_Browse3(Fl_Button*, void*);
public:
  Fl_Button *m_close;
private:
  inline void cb_m_close_i(Fl_Button*, void*);
  static void cb_m_close(Fl_Button*, void*);
};
#endif
